[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src  'self' https://apis.google.com;
      style-src   'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      font-src    'self' https://fonts.googleapis.com https://fonts.gstatic.com https://cdnjs.cloudflare.com data:;
      img-src     'self' data: https:;
      connect-src 'self' https://acadmix.shop https://api.acadmix.shop;
    """

[[redirects]]
  from = "/api/*"
  to = "https://api.acadmix.shop/api/:splat"
  status = 200
  force = true
